services:
  database:
    image: 'postgres:16.3'
    container_name: fullstack-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: db_postgres
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fullstack-backend
    ports:
      - "3001:3001"
    depends_on: 
      - database   
    environment:  
      DATABASE_URL: postgresql://usuario:senha@database:5432/db_postgres?schema=public

  frontend:
    build: ./frontend
    container_name: fullstack-frontend
    depends_on: 
      - backend
    volumes:
      - front-volume:/var/www/html

  nginx:
    build: ./nginx
    container_name: fullstack-nginx
    ports:
      - "81:81"
    volumes:
      - front-volume:/var/www/html
    depends_on:
      - backend
      - frontend  

volumes:
  postgres-data:
  front-volume: